# dbt project — lives in folder dbt/
name: 'ey_fakestore'
version: '1.0.0'
config-version: 2

profile: 'dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ey_fakestore:
    staging:
      +materialized: view
    marts:
      +materialized: table
